# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'camera_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61mera_stream.proto\x12\rcamera_stream\"\x0e\n\x0c\x45mptyRequest\"\xa2\x01\n\x0b\x43\x61meraFrame\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x04\x12\x11\n\tstamp_sec\x18\x02 \x01(\x03\x12\x15\n\rstamp_nanosec\x18\x03 \x01(\r\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\t\x12\r\n\x05width\x18\x05 \x01(\r\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x07 \x01(\t\x12\x11\n\tjpeg_data\x18\x08 \x01(\x0c\x32Y\n\x0c\x43\x61meraStream\x12I\n\x0cStreamFrames\x12\x1b.camera_stream.EmptyRequest\x1a\x1a.camera_stream.CameraFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=38
  _globals['_EMPTYREQUEST']._serialized_end=52
  _globals['_CAMERAFRAME']._serialized_start=55
  _globals['_CAMERAFRAME']._serialized_end=217
  _globals['_CAMERASTREAM']._serialized_start=219
  _globals['_CAMERASTREAM']._serialized_end=308
# @@protoc_insertion_point(module_scope)
